# Enable USB logging on peripheral side for debugging
CONFIG_ZMK_USB_LOGGING=y
CONFIG_USB_CDC_ACM=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=4000
CONFIG_PINNACLE_LOG_LEVEL_DBG=y
CONFIG_INPUT_LOG_LEVEL_DBG=y
